/*
 * ICARUS API
 * The API allows an organization to have access to most of their ICARUS data!
 *
 * OpenAPI spec version: 2.0
 * Contact: support@icarusops.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.icarus.synchronization.postsyncmodel;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * AddAndUpdateAssignedWarningObject
 */

public class AddAndUpdateAssignedWarningObject extends AssignedObjects {
  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;

  public static final String SERIALIZED_NAME_ASSIGNED_CHECKLIST_UUID = "assigned_checklist_uuid";
  @SerializedName(SERIALIZED_NAME_ASSIGNED_CHECKLIST_UUID)
  private String assignedChecklistUuid;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Integer userId;

  public static final String SERIALIZED_NAME_WARNING_ID = "warning_id";
  @SerializedName(SERIALIZED_NAME_WARNING_ID)
  private Integer warningId;

  public static final String SERIALIZED_NAME_CHECKLIST_ELEMENT_ID = "checklist_element_id";
  @SerializedName(SERIALIZED_NAME_CHECKLIST_ELEMENT_ID)
  private Integer checklistElementId;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDING("pending"),
    
    ACKNOWLEDGED("acknowledged"),
    
    SKIPPED("skipped"),
    
    DEFERRED("deferred");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  public static final String SERIALIZED_NAME_IS_DELETED = "is_deleted";
  @SerializedName(SERIALIZED_NAME_IS_DELETED)
  private Boolean isDeleted;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public AddAndUpdateAssignedWarningObject uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(example = "2284b7f6-81c4-11e4-89d3-00ffd0b164b9", required = true, value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public AddAndUpdateAssignedWarningObject assignedChecklistUuid(String assignedChecklistUuid) {
    this.assignedChecklistUuid = assignedChecklistUuid;
    return this;
  }

   /**
   * Get assignedChecklistUuid
   * @return assignedChecklistUuid
  **/
  @ApiModelProperty(example = "2284b7f6-81c4-11e4-89d3-00ffd0b164b9", required = true, value = "")
  public String getAssignedChecklistUuid() {
    return assignedChecklistUuid;
  }

  public void setAssignedChecklistUuid(String assignedChecklistUuid) {
    this.assignedChecklistUuid = assignedChecklistUuid;
  }

  public AddAndUpdateAssignedWarningObject userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public AddAndUpdateAssignedWarningObject warningId(Integer warningId) {
    this.warningId = warningId;
    return this;
  }

   /**
   * Get warningId
   * @return warningId
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getWarningId() {
    return warningId;
  }

  public void setWarningId(Integer warningId) {
    this.warningId = warningId;
  }

  public AddAndUpdateAssignedWarningObject checklistElementId(Integer checklistElementId) {
    this.checklistElementId = checklistElementId;
    return this;
  }

   /**
   * Get checklistElementId
   * @return checklistElementId
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getChecklistElementId() {
    return checklistElementId;
  }

  public void setChecklistElementId(Integer checklistElementId) {
    this.checklistElementId = checklistElementId;
  }

  public AddAndUpdateAssignedWarningObject status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "pending", required = true, value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public AddAndUpdateAssignedWarningObject isDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

   /**
   * Get isDeleted
   * @return isDeleted
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  public AddAndUpdateAssignedWarningObject createdAt(String  createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String  createdAt) {
    this.createdAt = createdAt;
  }

  public AddAndUpdateAssignedWarningObject updatedAt(String  updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(required = true, value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String  updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddAndUpdateAssignedWarningObject addAndUpdateAssignedWarningObject = (AddAndUpdateAssignedWarningObject) o;
    return Objects.equals(this.uuid, addAndUpdateAssignedWarningObject.uuid) &&
        Objects.equals(this.assignedChecklistUuid, addAndUpdateAssignedWarningObject.assignedChecklistUuid) &&
        Objects.equals(this.userId, addAndUpdateAssignedWarningObject.userId) &&
        Objects.equals(this.warningId, addAndUpdateAssignedWarningObject.warningId) &&
        Objects.equals(this.checklistElementId, addAndUpdateAssignedWarningObject.checklistElementId) &&
        Objects.equals(this.status, addAndUpdateAssignedWarningObject.status) &&
        Objects.equals(this.isDeleted, addAndUpdateAssignedWarningObject.isDeleted) &&
        Objects.equals(this.createdAt, addAndUpdateAssignedWarningObject.createdAt) &&
        Objects.equals(this.updatedAt, addAndUpdateAssignedWarningObject.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, assignedChecklistUuid, userId, warningId, checklistElementId, status, isDeleted, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddAndUpdateAssignedWarningObject {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    assignedChecklistUuid: ").append(toIndentedString(assignedChecklistUuid)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    warningId: ").append(toIndentedString(warningId)).append("\n");
    sb.append("    checklistElementId: ").append(toIndentedString(checklistElementId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

