/*
 * ICARUS API
 * The API allows an organization to have access to most of their ICARUS data!
 *
 * OpenAPI spec version: 2.0
 * Contact: support@icarusops.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.icarus.synchronization.postsyncmodel;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * AddANdUpdateAssignedStepObject
 */

public class AddANdUpdateAssignedStepObject extends AssignedObjects {
  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;

  public static final String SERIALIZED_NAME_ASSIGNED_CHECKLIST_UUID = "assigned_checklist_uuid";
  @SerializedName(SERIALIZED_NAME_ASSIGNED_CHECKLIST_UUID)
  private String assignedChecklistUuid;

  public static final String SERIALIZED_NAME_CHECKLIST_ELEMENT_ID = "checklist_element_id";
  @SerializedName(SERIALIZED_NAME_CHECKLIST_ELEMENT_ID)
  private Integer checklistElementId;

  public static final String SERIALIZED_NAME_STEP_ID = "step_id";
  @SerializedName(SERIALIZED_NAME_STEP_ID)
  private Integer stepId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Integer userId;

  public static final String SERIALIZED_NAME_IS_DELETED = "is_deleted";
  @SerializedName(SERIALIZED_NAME_IS_DELETED)
  private Boolean isDeleted;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public AddANdUpdateAssignedStepObject uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(example = "fc343caa-3bc3-4e16-8b28-c4b92a0ed2de", required = true, value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public AddANdUpdateAssignedStepObject assignedChecklistUuid(String assignedChecklistUuid) {
    this.assignedChecklistUuid = assignedChecklistUuid;
    return this;
  }

   /**
   * Get assignedChecklistUuid
   * @return assignedChecklistUuid
  **/
  @ApiModelProperty(example = "fc343caa-3bc3-4e16-8b28-c4b92a0ed2de", required = true, value = "")
  public String getAssignedChecklistUuid() {
    return assignedChecklistUuid;
  }

  public void setAssignedChecklistUuid(String assignedChecklistUuid) {
    this.assignedChecklistUuid = assignedChecklistUuid;
  }

  public AddANdUpdateAssignedStepObject checklistElementId(Integer checklistElementId) {
    this.checklistElementId = checklistElementId;
    return this;
  }

   /**
   * Get checklistElementId
   * @return checklistElementId
  **/
  @ApiModelProperty(example = "2", required = true, value = "")
  public Integer getChecklistElementId() {
    return checklistElementId;
  }

  public void setChecklistElementId(Integer checklistElementId) {
    this.checklistElementId = checklistElementId;
  }

  public AddANdUpdateAssignedStepObject stepId(Integer stepId) {
    this.stepId = stepId;
    return this;
  }

   /**
   * Get stepId
   * @return stepId
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getStepId() {
    return stepId;
  }

  public void setStepId(Integer stepId) {
    this.stepId = stepId;
  }

  public AddANdUpdateAssignedStepObject status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "completed", required = true, value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public AddANdUpdateAssignedStepObject userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "4", required = true, value = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public AddANdUpdateAssignedStepObject isDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

   /**
   * Get isDeleted
   * @return isDeleted
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  public AddANdUpdateAssignedStepObject createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "2016-04-19 07:22:32", required = true, value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public AddANdUpdateAssignedStepObject updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2016-04-19 07:22:35", required = true, value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddANdUpdateAssignedStepObject addANdUpdateAssignedStepObject = (AddANdUpdateAssignedStepObject) o;
    return Objects.equals(this.uuid, addANdUpdateAssignedStepObject.uuid) &&
        Objects.equals(this.assignedChecklistUuid, addANdUpdateAssignedStepObject.assignedChecklistUuid) &&
        Objects.equals(this.checklistElementId, addANdUpdateAssignedStepObject.checklistElementId) &&
        Objects.equals(this.stepId, addANdUpdateAssignedStepObject.stepId) &&
        Objects.equals(this.status, addANdUpdateAssignedStepObject.status) &&
        Objects.equals(this.userId, addANdUpdateAssignedStepObject.userId) &&
        Objects.equals(this.isDeleted, addANdUpdateAssignedStepObject.isDeleted) &&
        Objects.equals(this.createdAt, addANdUpdateAssignedStepObject.createdAt) &&
        Objects.equals(this.updatedAt, addANdUpdateAssignedStepObject.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, assignedChecklistUuid, checklistElementId, stepId, status, userId, isDeleted, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddANdUpdateAssignedStepObject {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    assignedChecklistUuid: ").append(toIndentedString(assignedChecklistUuid)).append("\n");
    sb.append("    checklistElementId: ").append(toIndentedString(checklistElementId)).append("\n");
    sb.append("    stepId: ").append(toIndentedString(stepId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

