/*
 * ICARUS API
 * The API allows an organization to have access to most of their ICARUS data!
 *
 * OpenAPI spec version: 2.0
 * Contact: support@icarusops.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.icarus.synchronization.postsyncmodel;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * AddANdUpdateAssignedStepObject
 */

public class AddANdUpdateAssignedLogoObject extends AssignedObjects {
  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;

  public static final String SERIALIZED_NAME_ASSIGNED_CHECKLIST_UUID = "assigned_checklist_uuid";
  @SerializedName(SERIALIZED_NAME_ASSIGNED_CHECKLIST_UUID)
  private String assignedChecklistUuid;

  public static final String SERIALIZED_NAME_CHECKLIST_LOGO_ID = "checklist_logo_id";
  @SerializedName(SERIALIZED_NAME_CHECKLIST_LOGO_ID)
  private Integer checklistLogoId;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public AddANdUpdateAssignedLogoObject uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(example = "fc343caa-3bc3-4e16-8b28-c4b92a0ed2de", required = true, value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public AddANdUpdateAssignedLogoObject assignedChecklistUuid(String assignedChecklistUuid) {
    this.assignedChecklistUuid = assignedChecklistUuid;
    return this;
  }

   /**
   * Get assignedChecklistUuid
   * @return assignedChecklistUuid
  **/
  @ApiModelProperty(example = "fc343caa-3bc3-4e16-8b28-c4b92a0ed2de", required = true, value = "")
  public String getAssignedChecklistUuid() {
    return assignedChecklistUuid;
  }

  public void setAssignedChecklistUuid(String assignedChecklistUuid) {
    this.assignedChecklistUuid = assignedChecklistUuid;
  }

  public AddANdUpdateAssignedLogoObject checklistElementId(Integer checklistElementId) {
    this.checklistLogoId = checklistElementId;
    return this;
  }

   /**
   * Get checklistLogoId
   * @return checklistLogoId
  **/
  @ApiModelProperty(example = "2", required = true, value = "")
  public Integer getChecklistLogoId() {
    return checklistLogoId;
  }

  public void setChecklistLogoId(Integer checklistLogoId) {
    this.checklistLogoId = checklistLogoId;
  }

  public AddANdUpdateAssignedLogoObject createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "2016-04-19 07:22:32", required = true, value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public AddANdUpdateAssignedLogoObject updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2016-04-19 07:22:35", required = true, value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddANdUpdateAssignedLogoObject addANdUpdateAssignedStepObject = (AddANdUpdateAssignedLogoObject) o;
    return Objects.equals(this.uuid, addANdUpdateAssignedStepObject.uuid) &&
        Objects.equals(this.assignedChecklistUuid, addANdUpdateAssignedStepObject.assignedChecklistUuid) &&
        Objects.equals(this.checklistLogoId, addANdUpdateAssignedStepObject.checklistLogoId) &&
        Objects.equals(this.createdAt, addANdUpdateAssignedStepObject.createdAt) &&
        Objects.equals(this.updatedAt, addANdUpdateAssignedStepObject.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, assignedChecklistUuid, checklistLogoId, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddANdUpdateAssignedStepObject {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    assignedChecklistUuid: ").append(toIndentedString(assignedChecklistUuid)).append("\n");
    sb.append("    checklistLogoId: ").append(toIndentedString(checklistLogoId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

