/*
 * ICARUS API
 * The API allows an organization to have access to most of their ICARUS data!
 *
 * OpenAPI spec version: 2.0
 * Contact: support@icarusops.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.icarus.synchronization.postsyncmodel;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * AddANdUpdateAssignedStepObject
 */

public class AddANdUpdateAssignedChecklistCommentObject extends AssignedObjects {
  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;

  public static final String SERIALIZED_NAME_ASSIGNED_CHECKLIST_UUID = "assigned_checklist_uuid";
  @SerializedName(SERIALIZED_NAME_ASSIGNED_CHECKLIST_UUID)
  private String assignedChecklistUuid;

  public static final String SERIALIZED_NAME_CHECKLIST_ID = "checklist_id";
  @SerializedName(SERIALIZED_NAME_CHECKLIST_ID)
  private Integer checklistId;

  public static final String SERIALIZED_NAME_CHECKLIST_ELEMENT_ID = "checklist_element_id";
  @SerializedName(SERIALIZED_NAME_CHECKLIST_ELEMENT_ID)
  private Integer checklistElementId;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Integer userId;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private String comment;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public AddANdUpdateAssignedChecklistCommentObject uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(example = "fc343caa-3bc3-4e16-8b28-c4b92a0ed2de", required = true, value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public AddANdUpdateAssignedChecklistCommentObject assignedChecklistUuid(String assignedChecklistUuid) {
    this.assignedChecklistUuid = assignedChecklistUuid;
    return this;
  }

   /**
   * Get assignedChecklistUuid
   * @return assignedChecklistUuid
  **/
  @ApiModelProperty(example = "fc343caa-3bc3-4e16-8b28-c4b92a0ed2de", required = true, value = "")
  public String getAssignedChecklistUuid() {
    return assignedChecklistUuid;
  }

  public void setAssignedChecklistUuid(String assignedChecklistUuid) {
    this.assignedChecklistUuid = assignedChecklistUuid;
  }

  public AddANdUpdateAssignedChecklistCommentObject checklistId(Integer checklistId) {
    this.checklistId = checklistId;
    return this;
  }

  /**
   * Get checklistId
   * @return checklistId
   **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getChecklistId() {
    return checklistId;
  }

  public void setChecklistId(Integer checklistId) {
    this.checklistId = checklistId;
  }

  public AddANdUpdateAssignedChecklistCommentObject checklistElementId(Integer checklistElementId) {
    this.checklistElementId = checklistElementId;
    return this;
  }

  /**
   * Get checklistElementId
   * @return checklistElementId
   **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getChecklistElementId() {
    return checklistElementId;
  }

  public void setChecklistElementId(Integer checklistElementId) {
    this.checklistElementId = checklistElementId;
  }

  public AddANdUpdateAssignedChecklistCommentObject comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @ApiModelProperty(example = "Comment", required = true, value = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public AddANdUpdateAssignedChecklistCommentObject userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "4", required = true, value = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public AddANdUpdateAssignedChecklistCommentObject createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "2016-04-19 07:22:32", required = true, value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public AddANdUpdateAssignedChecklistCommentObject updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2016-04-19 07:22:35", required = true, value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddANdUpdateAssignedChecklistCommentObject addANdUpdateAssignedStepObject = (AddANdUpdateAssignedChecklistCommentObject) o;
    return Objects.equals(this.uuid, addANdUpdateAssignedStepObject.uuid) &&
        Objects.equals(this.assignedChecklistUuid, addANdUpdateAssignedStepObject.assignedChecklistUuid) &&
        Objects.equals(this.checklistId, addANdUpdateAssignedStepObject.checklistId) &&
        Objects.equals(this.checklistElementId, addANdUpdateAssignedStepObject.checklistElementId) &&
        Objects.equals(this.userId, addANdUpdateAssignedStepObject.userId) &&
        Objects.equals(this.comment, addANdUpdateAssignedStepObject.comment) &&
        Objects.equals(this.createdAt, addANdUpdateAssignedStepObject.createdAt) &&
        Objects.equals(this.updatedAt, addANdUpdateAssignedStepObject.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, assignedChecklistUuid, checklistId, checklistElementId, userId, comment, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddANdUpdateAssignedStepObject {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    assignedChecklistUuid: ").append(toIndentedString(assignedChecklistUuid)).append("\n");
    sb.append("    checklistId: ").append(toIndentedString(checklistId)).append("\n");
    sb.append("    checklistElementId: ").append(toIndentedString(checklistElementId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

