/*
 * ICARUS API
 * The API allows an organization to have access to most of their ICARUS data!
 *
 * OpenAPI spec version: 2.0
 * Contact: support@icarusops.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.icarus.synchronization.postsyncmodel;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * AddAndUpdateAssignedStepResourceObject
 */

public class AddAndUpdateAssignedStepResourceObject extends AssignedObjects {
  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;

  public static final String SERIALIZED_NAME_ASSIGNED_CHECKLIST_UUID = "assigned_checklist_uuid";
  @SerializedName(SERIALIZED_NAME_ASSIGNED_CHECKLIST_UUID)
  private String assignedChecklistUuid;

  public static final String SERIALIZED_NAME_CHECKLIST_ELEMENT_ID = "checklist_element_id";
  @SerializedName(SERIALIZED_NAME_CHECKLIST_ELEMENT_ID)
  private Integer checklistElementId;

  public static final String SERIALIZED_NAME_ITEM_TYPE_ID = "item_type_id";
  @SerializedName(SERIALIZED_NAME_ITEM_TYPE_ID)
  private Integer itemTypeId;

  public static final String SERIALIZED_NAME_ITEM_ID = "item_id";
  @SerializedName(SERIALIZED_NAME_ITEM_ID)
  private Integer itemId;

  public static final String SERIALIZED_NAME_DISPLAY_FILENAME = "display_filename";
  @SerializedName(SERIALIZED_NAME_DISPLAY_FILENAME)
  private String displayFilename;

  public static final String SERIALIZED_NAME_FILENAME = "filename";
  @SerializedName(SERIALIZED_NAME_FILENAME)
  private String filename;

  public static final String SERIALIZED_NAME_MD5_CHECKSUM = "md5_checksum";
  @SerializedName(SERIALIZED_NAME_MD5_CHECKSUM)
  private String md5Checksum;

  public static final String SERIALIZED_NAME_CONTENT_TYPE = "content_type";
  @SerializedName(SERIALIZED_NAME_CONTENT_TYPE)
  private String contentType;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Integer userId;

  public static final String SERIALIZED_NAME_IS_DELETED = "is_deleted";
  @SerializedName(SERIALIZED_NAME_IS_DELETED)
  private Boolean isDeleted;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public AddAndUpdateAssignedStepResourceObject uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(example = "f71214a3-5b23-4fc1-87ae-e6a77f567a9f", required = true, value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public AddAndUpdateAssignedStepResourceObject assignedChecklistUuid(String assignedChecklistUuid) {
    this.assignedChecklistUuid = assignedChecklistUuid;
    return this;
  }

   /**
   * Get assignedChecklistUuid
   * @return assignedChecklistUuid
  **/
  @ApiModelProperty(example = "fc343caa-3bc3-4e16-8b28-c4b92a0ed2de", required = true, value = "")
  public String getAssignedChecklistUuid() {
    return assignedChecklistUuid;
  }

  public void setAssignedChecklistUuid(String assignedChecklistUuid) {
    this.assignedChecklistUuid = assignedChecklistUuid;
  }

  public AddAndUpdateAssignedStepResourceObject checklistElementId(Integer checklistElementId) {
    this.checklistElementId = checklistElementId;
    return this;
  }

   /**
   * Get checklistElementId
   * @return checklistElementId
  **/
  @ApiModelProperty(example = "2", required = true, value = "")
  public Integer getChecklistElementId() {
    return checklistElementId;
  }

  public void setChecklistElementId(Integer checklistElementId) {
    this.checklistElementId = checklistElementId;
  }

  public AddAndUpdateAssignedStepResourceObject itemTypeId(Integer itemTypeId) {
    this.itemTypeId = itemTypeId;
    return this;
  }

   /**
   * Get itemTypeId
   * @return itemTypeId
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getItemTypeId() {
    return itemTypeId;
  }

  public void setItemTypeId(Integer itemTypeId) {
    this.itemTypeId = itemTypeId;
  }

  public AddAndUpdateAssignedStepResourceObject itemId(Integer itemId) {
    this.itemId = itemId;
    return this;
  }

   /**
   * Get itemId
   * @return itemId
  **/
  @ApiModelProperty(example = "13", required = true, value = "")
  public Integer getItemId() {
    return itemId;
  }

  public void setItemId(Integer itemId) {
    this.itemId = itemId;
  }

  public AddAndUpdateAssignedStepResourceObject displayFilename(String displayFilename) {
    this.displayFilename = displayFilename;
    return this;
  }

   /**
   * Get displayFilename
   * @return displayFilename
  **/
  @ApiModelProperty(example = "IMG_20160322_112325.jpg", required = true, value = "")
  public String getDisplayFilename() {
    return displayFilename;
  }

  public void setDisplayFilename(String displayFilename) {
    this.displayFilename = displayFilename;
  }

  public AddAndUpdateAssignedStepResourceObject filename(String filename) {
    this.filename = filename;
    return this;
  }

   /**
   * Get filename
   * @return filename
  **/
  @ApiModelProperty(example = "20160418_11_21_52.jpeg", required = true, value = "")
  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public AddAndUpdateAssignedStepResourceObject md5Checksum(String md5Checksum) {
    this.md5Checksum = md5Checksum;
    return this;
  }

   /**
   * Get md5Checksum
   * @return md5Checksum
  **/
  @ApiModelProperty(example = "c8e7e1fc344be6982710f54d47191ef6", required = true, value = "")
  public String getMd5Checksum() {
    return md5Checksum;
  }

  public void setMd5Checksum(String md5Checksum) {
    this.md5Checksum = md5Checksum;
  }

  public AddAndUpdateAssignedStepResourceObject contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Get contentType
   * @return contentType
  **/
  @ApiModelProperty(example = "image/jpeg", required = true, value = "")
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  public AddAndUpdateAssignedStepResourceObject userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "1209", required = true, value = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public AddAndUpdateAssignedStepResourceObject isDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

   /**
   * Get isDeleted
   * @return isDeleted
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }

  public AddAndUpdateAssignedStepResourceObject createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "2016-04-18 11:22:00", required = true, value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public AddAndUpdateAssignedStepResourceObject updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2016-04-19 07:19:54", required = true, value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddAndUpdateAssignedStepResourceObject addAndUpdateAssignedStepResourceObject = (AddAndUpdateAssignedStepResourceObject) o;
    return Objects.equals(this.uuid, addAndUpdateAssignedStepResourceObject.uuid) &&
        Objects.equals(this.assignedChecklistUuid, addAndUpdateAssignedStepResourceObject.assignedChecklistUuid) &&
        Objects.equals(this.checklistElementId, addAndUpdateAssignedStepResourceObject.checklistElementId) &&
        Objects.equals(this.itemTypeId, addAndUpdateAssignedStepResourceObject.itemTypeId) &&
        Objects.equals(this.itemId, addAndUpdateAssignedStepResourceObject.itemId) &&
        Objects.equals(this.displayFilename, addAndUpdateAssignedStepResourceObject.displayFilename) &&
        Objects.equals(this.filename, addAndUpdateAssignedStepResourceObject.filename) &&
        Objects.equals(this.md5Checksum, addAndUpdateAssignedStepResourceObject.md5Checksum) &&
        Objects.equals(this.contentType, addAndUpdateAssignedStepResourceObject.contentType) &&
        Objects.equals(this.userId, addAndUpdateAssignedStepResourceObject.userId) &&
        Objects.equals(this.isDeleted, addAndUpdateAssignedStepResourceObject.isDeleted) &&
        Objects.equals(this.createdAt, addAndUpdateAssignedStepResourceObject.createdAt) &&
        Objects.equals(this.updatedAt, addAndUpdateAssignedStepResourceObject.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, assignedChecklistUuid, checklistElementId, itemTypeId, itemId, displayFilename, filename, md5Checksum, contentType, userId, isDeleted, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddAndUpdateAssignedStepResourceObject {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    assignedChecklistUuid: ").append(toIndentedString(assignedChecklistUuid)).append("\n");
    sb.append("    checklistElementId: ").append(toIndentedString(checklistElementId)).append("\n");
    sb.append("    itemTypeId: ").append(toIndentedString(itemTypeId)).append("\n");
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    displayFilename: ").append(toIndentedString(displayFilename)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    md5Checksum: ").append(toIndentedString(md5Checksum)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

