/*
 * ICARUS API
 * The API allows an organization to have access to most of their ICARUS data!
 *
 * OpenAPI spec version: 2.0
 * Contact: support@icarusops.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.icarus.synchronization.postsyncmodel;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * AssignedChecklistPauseTimeObject
 */

public class AssignedChecklistPauseTimeObject extends AssignedObjects {
    public static final String SERIALIZED_NAME_UUID = "uuid";
    @SerializedName(SERIALIZED_NAME_UUID)
    private String uuid;

    public static final String SERIALIZED_NAME_ASSIGNED_CHECKLIST_UUID = "assigned_checklist_uuid";
    @SerializedName(SERIALIZED_NAME_ASSIGNED_CHECKLIST_UUID)
    private String assignedChecklistUuid;

    public static final String SERIALIZED_NAME_USER_ID = "user_id";
    @SerializedName(SERIALIZED_NAME_USER_ID)
    private Integer userId;

    public static final String SERIALIZED_NAME_RESUME_BY_USER_ID = "resumed_by_user_id";
    @SerializedName(SERIALIZED_NAME_RESUME_BY_USER_ID)
    private Integer resumedByUserId;

    public static final String SERIALIZED_NAME_REASON = "reason";
    @SerializedName(SERIALIZED_NAME_REASON)
    private String reason;

    public static final String SERIALIZED_NAME_IS_PAUSED = "is_paused";
    @SerializedName(SERIALIZED_NAME_IS_PAUSED)
    private boolean isPaused;

    public static final String SERIALIZED_NAME_IS_DELETED = "is_deleted";
    @SerializedName(SERIALIZED_NAME_IS_DELETED)
    private Boolean isDeleted;

    public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
    @SerializedName(SERIALIZED_NAME_CREATED_AT)
    private String createdAt;

    public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
    @SerializedName(SERIALIZED_NAME_UPDATED_AT)
    private String updatedAt;

    public AssignedChecklistPauseTimeObject uuid(String uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * Get uuid
     *
     * @return uuid
     **/
    @ApiModelProperty(example = "2284b7f6-81c4-11e4-89d3-00ffd0b164b9", required = true, value = "")
    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public AssignedChecklistPauseTimeObject assignedChecklistUuid(String assignedChecklistUuid) {
        this.assignedChecklistUuid = assignedChecklistUuid;
        return this;
    }

    /**
     * Get assignedChecklistUuid
     *
     * @return assignedChecklistUuid
     **/
    @ApiModelProperty(example = "2284b7f6-81c4-11e4-89d3-00ffd0b164b9", required = true, value = "")
    public String getAssignedChecklistUuid() {
        return assignedChecklistUuid;
    }

    public void setAssignedChecklistUuid(String assignedChecklistUuid) {
        this.assignedChecklistUuid = assignedChecklistUuid;
    }

    public AssignedChecklistPauseTimeObject userId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Get userId
     *
     * @return userId
     **/
    @ApiModelProperty(example = "1", required = true, value = "")
    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public AssignedChecklistPauseTimeObject resumedByUserId(Integer resumedByUserId) {
        this.resumedByUserId = resumedByUserId;
        return this;
    }

    /**
     * Get resumedByUserId
     *
     * @return resumedByUserId
     **/
    @ApiModelProperty(example = "1", required = false, value = "")
    public Integer getResumedByUserId() {
        return resumedByUserId;
    }

    public void setResumedByUserId(Integer resumedByUserId) {
        this.resumedByUserId = resumedByUserId;
    }

    /**
     * Get reason
     *
     * @return reason
     **/
    @ApiModelProperty(required = true, value = "")
    public AssignedChecklistPauseTimeObject reason(String reason) {
        this.reason = reason;
        return this;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public AssignedChecklistPauseTimeObject isPaused(Boolean isPaused) {
        this.isPaused = isPaused;
        return this;
    }

    /**
     * Get isDeleted
     *
     * @return isDeleted
     **/
    @ApiModelProperty(required = true, value = "")
    public boolean getIsPaused() {
        return isPaused;
    }

    public void setIsPaused(boolean paused) {
        isPaused = paused;
    }

    public AssignedChecklistPauseTimeObject isDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
        return this;
    }

    /**
     * Get isDeleted
     *
     * @return isDeleted
     **/
    @ApiModelProperty(required = true, value = "")
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(Boolean deleted) {
        isDeleted = deleted;
    }

    public AssignedChecklistPauseTimeObject createdAt(String createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Get createdAt
     *
     * @return createdAt
     **/
    @ApiModelProperty(required = true, value = "")
    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public AssignedChecklistPauseTimeObject updatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Get updatedAt
     *
     * @return updatedAt
     **/
    @ApiModelProperty(required = true, value = "")
    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AssignedChecklistPauseTimeObject AssignedChecklistPauseTimeObject = (AssignedChecklistPauseTimeObject) o;
        return Objects.equals(this.uuid, AssignedChecklistPauseTimeObject.uuid) &&
                Objects.equals(this.assignedChecklistUuid, AssignedChecklistPauseTimeObject.assignedChecklistUuid) &&
                Objects.equals(this.userId, AssignedChecklistPauseTimeObject.userId) &&
                Objects.equals(this.resumedByUserId, AssignedChecklistPauseTimeObject.resumedByUserId) &&
                Objects.equals(this.reason, AssignedChecklistPauseTimeObject.reason) &&
                Objects.equals(this.isPaused, AssignedChecklistPauseTimeObject.isPaused) &&
                Objects.equals(this.isDeleted, AssignedChecklistPauseTimeObject.isDeleted) &&
                Objects.equals(this.createdAt, AssignedChecklistPauseTimeObject.createdAt) &&
                Objects.equals(this.updatedAt, AssignedChecklistPauseTimeObject.updatedAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(uuid, assignedChecklistUuid, userId, resumedByUserId, reason, isPaused, isDeleted, createdAt, updatedAt);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AssignedChecklistPauseTimeObject {\n");

        sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
        sb.append("    assignedChecklistUuid: ").append(toIndentedString(assignedChecklistUuid)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("    resumedByUserId: ").append(toIndentedString(resumedByUserId)).append("\n");
        sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
        sb.append("    isPaused: ").append(toIndentedString(isPaused)).append("\n");
        sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
        sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
        sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

