/*
 * ICARUS API
 * The API allows an organization to have access to most of their ICARUS data!
 *
 * OpenAPI spec version: 2.0
 * Contact: support@icarusops.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.icarus.synchronization.postsyncmodel;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse2011
 */

public class AssignedAttributeUploadResponse {
  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;

  public static final String SERIALIZED_NAME_FILE_MD5_CHECKSUM = "file_md5_checksum";
  @SerializedName(SERIALIZED_NAME_FILE_MD5_CHECKSUM)
  private String fileMd5Checksum;

  public AssignedAttributeUploadResponse uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public AssignedAttributeUploadResponse fileMd5Checksum(String fileMd5Checksum) {
    this.fileMd5Checksum = fileMd5Checksum;
    return this;
  }

   /**
   * Get fileMd5Checksum
   * @return fileMd5Checksum
  **/
  @ApiModelProperty(value = "")
  public String getFileMd5Checksum() {
    return fileMd5Checksum;
  }

  public void setFileMd5Checksum(String fileMd5Checksum) {
    this.fileMd5Checksum = fileMd5Checksum;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssignedAttributeUploadResponse inlineResponse2011 = (AssignedAttributeUploadResponse) o;
    return Objects.equals(this.uuid, inlineResponse2011.uuid) &&
        Objects.equals(this.fileMd5Checksum, inlineResponse2011.fileMd5Checksum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, fileMd5Checksum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2011 {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    fileMd5Checksum: ").append(toIndentedString(fileMd5Checksum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

