/*
 * ICARUS API
 * The API allows an organization to have access to most of their ICARUS data!
 *
 * OpenAPI spec version: 2.0
 * Contact: support@icarusops.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.icarus.synchronization.postsyncmodel;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * UserSuggestionAttachmentObject
 */

public class UserSuggestionAttachmentObject extends AssignedObjects {
  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;

  public static final String SERIALIZED_NAME_USER_SUGGESTION_UUID = "user_suggestion_uuid";
  @SerializedName(SERIALIZED_NAME_USER_SUGGESTION_UUID)
  private String userSuggestionUuid;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Integer userId;

  public static final String SERIALIZED_NAME_DISPLAY_FILENAME = "display_filename";
  @SerializedName(SERIALIZED_NAME_DISPLAY_FILENAME)
  private String displayFilename;

  public static final String SERIALIZED_NAME_FILENAME = "filename";
  @SerializedName(SERIALIZED_NAME_FILENAME)
  private String filename;

  public static final String SERIALIZED_NAME_FILE_SIZE = "file_size";
  @SerializedName(SERIALIZED_NAME_FILE_SIZE)
  private BigDecimal fileSize;

  public static final String SERIALIZED_NAME_CONTENT_TYPE = "content_type";
  @SerializedName(SERIALIZED_NAME_CONTENT_TYPE)
  private String contentType;

  public static final String SERIALIZED_NAME_MD5_CHECKSUM = "md5_checksum";
  @SerializedName(SERIALIZED_NAME_MD5_CHECKSUM)
  private String md5Checksum;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public UserSuggestionAttachmentObject uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(example = "2284b7f6-81c4-11e4-89d3-00ffd0b164b9", required = true, value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public UserSuggestionAttachmentObject userSuggestionUuid(String userSuggestionUuid) {
    this.userSuggestionUuid = userSuggestionUuid;
    return this;
  }

   /**
   * Get userSuggestionUuid
   * @return userSuggestionUuid
  **/
  @ApiModelProperty(example = "2284b7f6-81c4-11e4-89d3-00ffd0b164b9", required = true, value = "")
  public String getUserSuggestionUuid() {
    return userSuggestionUuid;
  }

  public void setUserSuggestionUuid(String userSuggestionUuid) {
    this.userSuggestionUuid = userSuggestionUuid;
  }

  public UserSuggestionAttachmentObject userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public UserSuggestionAttachmentObject displayFilename(String displayFilename) {
    this.displayFilename = displayFilename;
    return this;
  }

   /**
   * Get displayFilename
   * @return displayFilename
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDisplayFilename() {
    return displayFilename;
  }

  public void setDisplayFilename(String displayFilename) {
    this.displayFilename = displayFilename;
  }

  public UserSuggestionAttachmentObject filename(String filename) {
    this.filename = filename;
    return this;
  }

   /**
   * Get filename
   * @return filename
  **/
  @ApiModelProperty(required = true, value = "")
  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public UserSuggestionAttachmentObject fileSize(BigDecimal fileSize) {
    this.fileSize = fileSize;
    return this;
  }

   /**
   * Get fileSize
   * @return fileSize
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getFileSize() {
    return fileSize;
  }

  public void setFileSize(BigDecimal fileSize) {
    this.fileSize = fileSize;
  }

  public UserSuggestionAttachmentObject contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Get contentType
   * @return contentType
  **/
  @ApiModelProperty(required = true, value = "")
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  public UserSuggestionAttachmentObject md5Checksum(String md5Checksum) {
    this.md5Checksum = md5Checksum;
    return this;
  }

   /**
   * Get md5Checksum
   * @return md5Checksum
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMd5Checksum() {
    return md5Checksum;
  }

  public void setMd5Checksum(String md5Checksum) {
    this.md5Checksum = md5Checksum;
  }

  public UserSuggestionAttachmentObject createdAt(String  createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String  createdAt) {
    this.createdAt = createdAt;
  }

  public UserSuggestionAttachmentObject updatedAt(String  updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(required = true, value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String  updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserSuggestionAttachmentObject userSuggestionAttachmentObject = (UserSuggestionAttachmentObject) o;
    return Objects.equals(this.uuid, userSuggestionAttachmentObject.uuid) &&
        Objects.equals(this.userSuggestionUuid, userSuggestionAttachmentObject.userSuggestionUuid) &&
        Objects.equals(this.userId, userSuggestionAttachmentObject.userId) &&
        Objects.equals(this.displayFilename, userSuggestionAttachmentObject.displayFilename) &&
        Objects.equals(this.filename, userSuggestionAttachmentObject.filename) &&
        Objects.equals(this.fileSize, userSuggestionAttachmentObject.fileSize) &&
        Objects.equals(this.contentType, userSuggestionAttachmentObject.contentType) &&
        Objects.equals(this.md5Checksum, userSuggestionAttachmentObject.md5Checksum) &&
        Objects.equals(this.createdAt, userSuggestionAttachmentObject.createdAt) &&
        Objects.equals(this.updatedAt, userSuggestionAttachmentObject.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, userSuggestionUuid, userId, displayFilename, filename, fileSize, contentType, md5Checksum, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserSuggestionAttachmentObject {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    userSuggestionUuid: ").append(toIndentedString(userSuggestionUuid)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    displayFilename: ").append(toIndentedString(displayFilename)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    md5Checksum: ").append(toIndentedString(md5Checksum)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

