/*
 * ICARUS API
 * The API allows an organization to have access to most of their ICARUS data!
 *
 * OpenAPI spec version: 2.0
 * Contact: support@icarusops.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.icarus.synchronization.syncmodels;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * RetrieveAllGroups
 */

public class RetrieveAllGroups {
  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private List<GroupObject> data = new ArrayList<GroupObject>();

  public static final String SERIALIZED_NAME_PAGINATION = "pagination";
  @SerializedName(SERIALIZED_NAME_PAGINATION)
  private Pagination pagination = null;

  public RetrieveAllGroups data(List<GroupObject> data) {
    this.data = data;
    return this;
  }

  public RetrieveAllGroups addDataItem(GroupObject dataItem) {
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(required = true, value = "")
  public List<GroupObject> getData() {
    return data;
  }

  public void setData(List<GroupObject> data) {
    this.data = data;
  }

  public RetrieveAllGroups pagination(Pagination pagination) {
    this.pagination = pagination;
    return this;
  }

   /**
   * Get pagination
   * @return pagination
  **/
  @ApiModelProperty(required = true, value = "")
  public Pagination getPagination() {
    return pagination;
  }

  public void setPagination(Pagination pagination) {
    this.pagination = pagination;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrieveAllGroups retrieveAllGroups = (RetrieveAllGroups) o;
    return Objects.equals(this.data, retrieveAllGroups.data) &&
        Objects.equals(this.pagination, retrieveAllGroups.pagination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, pagination);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrieveAllGroups {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  public class Pagination {

    @SerializedName("page")
    @Expose
    public Integer page;
    @SerializedName("per_page")
    @Expose
    public Integer perPage;
    @SerializedName("prev_url")
    @Expose
    public Object prevUrl;
    @SerializedName("next_url")
    @Expose
    public String nextUrl;

    public Integer getPage() {
      return page;
    }

    public void setPage(Integer page) {
      this.page = page;
    }

    public Integer getPerPage() {
      return perPage;
    }

    public void setPerPage(Integer perPage) {
      this.perPage = perPage;
    }

    public Object getPrevUrl() {
      return prevUrl;
    }

    public void setPrevUrl(Object prevUrl) {
      this.prevUrl = prevUrl;
    }

    public String getNextUrl() {
      return nextUrl;
    }

    public void setNextUrl(String nextUrl) {
      this.nextUrl = nextUrl;
    }
  }


}

