/*
 * ICARUS API
 * The API allows an organization to have access to most of their ICARUS data!
 *
 * OpenAPI spec version: 2.0
 * Contact: support@icarusops.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.icarus.synchronization.syncmodels;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;


/**
 * RetrieveAllWorkorderElements
 */

public class RetrieveAllWorkorderElements {
    @SerializedName("data")
    @Expose
    private WorkorderElement data = null;

    public WorkorderElement getData() {
        return data;
    }

    public void setData(WorkorderElement data) {
        this.data = data;
    }
}

