/*
 * ICARUS API
 * The API allows an organization to have access to most of their ICARUS data!
 *
 * OpenAPI spec version: 2.0
 * Contact: support@icarusops.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.icarus.synchronization.syncmodels;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * SyncMetaDataObject
 */

public class SyncMetaDataObject {
  public static final String SERIALIZED_NAME_SERVER_DATE_TIME = "ServerDateTime";
  @SerializedName(SERIALIZED_NAME_SERVER_DATE_TIME)
  private Integer serverDateTime;

  public static final String SERIALIZED_NAME_SERVER_DATE_TIME_FORMATTED = "ServerDateTimeFormatted";
  @SerializedName(SERIALIZED_NAME_SERVER_DATE_TIME_FORMATTED)
  private String serverDateTimeFormatted;

  public static final String SERIALIZED_NAME_REVISION = "Revision";
  @SerializedName(SERIALIZED_NAME_REVISION)
  private Integer revision;

  public SyncMetaDataObject serverDateTime(Integer serverDateTime) {
    this.serverDateTime = serverDateTime;
    return this;
  }

   /**
   * Get serverDateTime
   * @return serverDateTime
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getServerDateTime() {
    return serverDateTime;
  }

  public void setServerDateTime(Integer serverDateTime) {
    this.serverDateTime = serverDateTime;
  }

  public SyncMetaDataObject serverDateTimeFormatted(String  serverDateTimeFormatted) {
    this.serverDateTimeFormatted = serverDateTimeFormatted;
    return this;
  }

   /**
   * Get serverDateTimeFormatted
   * @return serverDateTimeFormatted
  **/
  @ApiModelProperty(required = true, value = "")
  public String getServerDateTimeFormatted() {
    return serverDateTimeFormatted;
  }

  public void setServerDateTimeFormatted(String  serverDateTimeFormatted) {
    this.serverDateTimeFormatted = serverDateTimeFormatted;
  }

  public SyncMetaDataObject revision(Integer revision) {
    this.revision = revision;
    return this;
  }

   /**
   * Get revision
   * @return revision
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getRevision() {
    return revision;
  }

  public void setRevision(Integer revision) {
    this.revision = revision;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SyncMetaDataObject syncMetaDataObject = (SyncMetaDataObject) o;
    return Objects.equals(this.serverDateTime, syncMetaDataObject.serverDateTime) &&
        Objects.equals(this.serverDateTimeFormatted, syncMetaDataObject.serverDateTimeFormatted) &&
        Objects.equals(this.revision, syncMetaDataObject.revision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serverDateTime, serverDateTimeFormatted, revision);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SyncMetaDataObject {\n");
    
    sb.append("    serverDateTime: ").append(toIndentedString(serverDateTime)).append("\n");
    sb.append("    serverDateTimeFormatted: ").append(toIndentedString(serverDateTimeFormatted)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

