/*
 * ICARUS API
 * The API allows an organization to have access to most of their ICARUS data!
 *
 * OpenAPI spec version: 2.0
 * Contact: support@icarusops.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.icarus.synchronization.syncmodels;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * UploadResponse
 */

public class WordorderUploadResponse {
  @SerializedName("data")
  @Expose
  public Data data;

  public Data getData() {
    return data;
  }

  public void setData(Data data) {
    this.data = data;
  }

  public static class Data {
    @SerializedName("uuid")
    @Expose
    public String uuid;

    @SerializedName("md5_checksum")
    @Expose
    public String fileMd5Checksum;

    public String getUuid() {
      return uuid;
    }

    public void setUuid(String uuid) {
      this.uuid = uuid;
    }

    public String getFileMd5Checksum() {
      return fileMd5Checksum;
    }

    public void setFileMd5Checksum(String fileMd5Checksum) {
      this.fileMd5Checksum = fileMd5Checksum;
    }
  }
}

